### ISSUE TITLE
WebSocket connection to XXX failed

### ISSUE THREAD

**Issue by Scit** [vmakhaev/reconnectable-websocket#13]
Hi! Got this error in Chrome:

"WebSocket connection to _<...>_ failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received"

The connection closes immediately after that.
Works fine in FF.

**Comment by vmakhaev** [comment]
Could you provide code sample?
Does it work with native web sockets?

**Comment by Scit** [comment]
I'm using it inside WebSocket wrapper component, like this:

```
import ReconnectableWebSocket from 'reconnectable-websocket';

export default class WebSocket {
  constructor(url) {
    this.socket = new ReconnectableWebSocket(`ws://${url}`, null, {...someOpts});
  }

  open() {
    this.socket.open();
  }
  ...
}
```

Now it works fine with https://github.com/joewalnes/reconnecting-websocket package. It has the same usage and option set but it's not supported at the moment.

**Comment by vmakhaev** [comment]
I guess it's because of bad handling of params.
Could you try this one?
```
this.socket = new ReconnectableWebSocket(`ws://${url}`, undefined, {...someOpts})
```

**Comment by Scit** [comment]
Yes! I've found the same!
Thank you for supporting! Now it works as expected.

**Comment by wesleytodd** [comment]
Should probably update the readme to reflect this

**Comment by Scit** [comment]
https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface

It seems, we should use empty array as the "protocols" param value

**Comment by wesleytodd** [comment]
I am not sure I agree.  I think servers might handle this differently than the current `undefined` behavior.  I have not tested it, but If I did not specify protocols, then I would not expect this library to change that to an empty array for me.

**Comment by vmakhaev** [comment]
Updated readme. Hope, it's enough.
