### ISSUE TITLE
Discussion of moving to events instead of overriding methods

### ISSUE THREAD

**Issue by wesleytodd** [vmakhaev/reconnectable-websocket#7]
It would seem fairly trivial to extend from the event emitter and both emit and call the methods.  The events I was thinking would be:
- `open`
- `error`
- `close`
- `reconnect`
- `message`

Thoughts? I will whip up a PR if you like the idea.

**Comment by vmakhaev** [comment]
I think it's better to use some wrapper for this, for [example](https://github.com/amelisa/amelisa/blob/master/src/client/WebSocketChannel.js), so we can stay as websocket-like api without any deps (event emitter).

**Comment by wesleytodd** [comment]
That is what we are doing currently.  But I would say that the event emitter isnt a dep since it is part of the standard lib.  Again, this was just to bring it up.  If you dont like it that is fine to :)
